# MySQL Configuration
- name: Install MySQL Packages
  yum: 
       name: "{{ item }}"
       state: latest
  loop: "{{ packages }}"

- name: Start mysqld service
  service:
       name: "{{ service }}"
       state: started
       enabled: yes

- name: Set MySQL root Password
  mysql_user:
    login_host: 'localhost'
    login_user: 'root'
    login_password: ''
    name: 'root'
    password: '{{ mysql_root_password }}'
    state: present
  ignore_errors: yes
 
- name: Creates database for WordPress
  mysql_db:
    name: "{{ mysql_db }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create MySQL user for WordPress
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_db }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"



